### ISSUE TITLE
angular fails with "invalid bytes in UTF8 string"

### ISSUE THREAD

**Issue by simon04** [freeCodeCamp/devdocs#1043]
```diff
diff --git a/lib/docs/scrapers/angular.rb b/lib/docs/scrapers/angular.rb
index 3365ec67..04f1cf5e 100644
--- a/lib/docs/scrapers/angular.rb
+++ b/lib/docs/scrapers/angular.rb
@@ -60,7 +62,7 @@ module Docs
 
     version do
       self.release = '6.0.4'
-      self.base_url = 'https://angular.io/'
+      self.base_url = 'https://v6.angular.io/'
       self.root_path = 'docs'
 
       html_filters.push 'angular/clean_html', 'angular/entries'

```

```
$ bundle exec thor docs:generate --force angular
Skipped large image (867 KB): https://v6.angular.io/generated/images/guide/dynamic-component-loader/ads.gif                                                                                                       
Skipped large image (277 KB): https://v6.angular.io/generated/images/guide/attribute-directives/highlight-directive-v2-anim.gif                                                                                   
Skipped large image (464 KB): https://v6.angular.io/generated/images/guide/attribute-directives/highlight-directive-final-anim.gif                                                                                
Skipped large image (277 KB): https://v6.angular.io/generated/images/guide/styleguide/use-extension.gif                                                                                                           
[#################################################################################################################################################################] [682/682] [100.00%] [00:50] [00:00] [ 13.39/s]bundler: failed to load command: thor (/home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/bin/thor)
JSON::ParserError: lexical error: invalid bytes in UTF8 string.
          "type":"\u0000V\u0000\u0000p�,A\u0000V\u0000\u0000\u0000\u00
                     (right here) ------^

  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:15:in `rescue in parse'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:11:in `parse'
  /home/simon/src/devdocs/lib/docs/subscribers/doc_subscriber.rb:45:in `parse_payload'
  /home/simon/src/devdocs/lib/docs/subscribers/doc_subscriber.rb:8:in `index'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/subscriber.rb:101:in `finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:104:in `finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `block in finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `each'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:44:in `finish_with_state'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:29:in `instrument'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
  /home/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:143:in `store_index'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:116:in `block in store_pages'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /home/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /home/simon/src/devdocs/lib/tasks/docs.thor:300:in `generate_doc'
  /home/simon/src/devdocs/lib/tasks/docs.thor:106:in `generate'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/bin/thor:23:in `load'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.6.0/bin/thor:23:in `<top (required)>'
```

**Comment by jmerle** [comment]
This issue has something to do with the types/classes in [https://angular.io/api/platform-webworker-dynamic](https://angular.io/api/platform-webworker-dynamic) and [https://angular.io/api/platform-browser-dynamic](https://angular.io/api/platform-browser-dynamic), although I haven't yet been able to find the exact cause.

**Comment by simon04** [comment]
Can no longer reproduce. It might have been an issue on the server which got fixed …
