### ISSUE TITLE
scraper-reference.md attribute "dir" not found

### ISSUE THREAD

**Issue by Lologoodtime** [freeCodeCamp/devdocs#1195]
Hi, in https://github.com/freeCodeCamp/devdocs/blob/master/docs/scraper-reference.md#attributes
It says we must use "dir" attribute with FileScraper but when i use it it's not found.
To solve this I used base_url with FileScraper even though it's required for UrlScraper.
So i just wanted to know if it's normal that in the documentation there is a part about "dir" but it's not available.
```Traceback (most recent call last):
19: from /usr/local/bundle/bin/thor:23:in `<main>'
18: from /usr/local/bundle/bin/thor:23:in `load'
17: from /usr/local/bundle/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
16: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
15: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
14: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
13: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
12: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
11: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
10: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
 9: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
 8: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
 7: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
 6: from /devdocs/lib/tasks/docs.thor:83:in `generate'
 5: from /devdocs/lib/docs.rb:60:in `find'
 4: from /devdocs/lib/docs.rb:60:in `const_get'
 3: from /devdocs/lib/docs.rb:60:in `require'
 2: from /devdocs/lib/docs/scrapers/nrgtester.rb:1:in `<top (required)>'
 1: from /devdocs/lib/docs/scrapers/nrgtester.rb:2:in `<module:Docs>'
/devdocs/lib/docs/scrapers/xxx.rb:7:in `<class:xxx>': undefined method `dir=' for Docs::Nrgtester:Class (NoMethodError)

**Comment by j-f1** [comment]
It looks like the docs are out of date. We changed how file scrapers work, so check out existing one, like C or Python to see how it’s done.

**Comment by Lologoodtime** [comment]
I manage to use it, thanks.
