### ISSUE TITLE
Bug: can not install new documentation on ms edge on windows v83.0.478.64

### ISSUE THREAD

**Issue by supersam5** [freeCodeCamp/devdocs#1254]
trying to install new documentations spawns 'oops... an error occured' there is also the 'please enable cookies' even though cookies are allowed, and i have exempted the app from all privacy settings
![Screenshot (172)](https://user-images.githubusercontent.com/26894514/87485787-811bc780-c631-11ea-9777-8cd79d5b9ecc.png)

> A cookie associated with a resource at http://devdocs.io/ was set with `SameSite=None` but without `Secure`. A future release of Microsoft Edge will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
```
application-f6f1ab042e931bc720962edfd90c6dc1459ec7b6c42d08e941a99e68c7df33c8.js:4220 Uncaught DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at t.idbTransaction (https://devdocs.io/assets/application-f6f1ab042e931bc720962edfd90c6dc1459ec7b6c42d08e941a99e68c7df33c8.js:4220:61)
    at https://devdocs.io/assets/application-f6f1ab042e931bc720962edfd90c6dc1459ec7b6c42d08e941a99e68c7df33c8.js:4063:18
    at t.runCallbacks (https://devdocs.io/assets/application-f6f1ab042e931bc720962edfd90c6dc1459ec7b6c42d08e941a99e68c7df33c8.js:4041:43)
    at t.onOpenSuccess (https://devdocs.io/assets/application-f6f1ab042e931bc720962edfd90c6dc1459ec7b6c42d08e941a99e68c7df33c8.js:3988:13)
    at IDBOpenDBRequest.<anonymous> (https://devdocs.io/assets/application-f6f1ab042e931bc720962edfd90c6dc1459ec7b6c42d08e941a99e68c7df33c8.js:3956:10)
```

**Comment by simon04** [comment]
`SameSite=Strict` and `secure=true` via b67cf41c0a0a0fae9247363060ac6535c9cffa15
