### ISSUE TITLE
Can't download DOM

### ISSUE THREAD

**Issue by gotheer** [freeCodeCamp/devdocs#1288]

**Comment by simon04** [comment]
```
$ bundle exec thor docs:generate --force dom
Fetching redirections...                                                                                                                                                                                                                                                                                                                             
Continuing...                                                                                                                                                                                                                                                                                                                                        
Building internal urls...                                                                                                                                                                                                                                                                                                                            
Continuing...                                                                                                                                                                                                                                                                                                                                        
bundler: failed to load command: thor (/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/bin/thor)
TypeError: no implicit conversion from nil to integer
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:47:in `ratio'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:101:in `render_bar'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:92:in `render'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:77:in `block in to_s'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:76:in `each'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:76:in `inject'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:76:in `to_s'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/progress_bar-1.3.0/lib/progress_bar.rb:39:in `write'
  /home/simon/src/devdocs/lib/docs/subscribers/progress_bar_subscriber.rb:11:in `running'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/subscriber.rb:101:in `finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:104:in `finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `block in finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `each'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `finish'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:44:in `finish_with_state'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:29:in `instrument'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
  /home/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /home/simon/src/devdocs/lib/docs/core/scraper.rb:74:in `build_pages'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:108:in `block in store_pages'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /home/simon/src/devdocs/lib/docs/core/scraper.rb:225:in `block in store_pages'
  /home/simon/src/devdocs/lib/docs/core/scraper.rb:233:in `with_internal_urls'
  /home/simon/src/devdocs/lib/docs/core/scraper.rb:223:in `store_pages'
  /home/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:144:in `block in store_pages'
  /home/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:152:in `with_redirections'
  /home/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:142:in `store_pages'
  /home/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /home/simon/src/devdocs/lib/tasks/docs.thor:300:in `generate_doc'
  /home/simon/src/devdocs/lib/tasks/docs.thor:106:in `generate'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/bin/thor:23:in `load'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/bin/thor:23:in `<top (required)>'
```

**Comment by simon04** [comment]
Duplicate of #1219
