### ISSUE TITLE
WindowOrWorkerGlobalScope.setInterval() is missing from the docs

### ISSUE THREAD

**Issue by bokonist** [freeCodeCamp/devdocs#1528]
## Summary
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval

this page is missing from the documentation

**Comment by simon04** [comment]
I cannot reproduce: https://devdocs.io/dom/windoworworkerglobalscope/settimeout

**Comment by ojeytonwilliams** [comment]
`setTimeout` has been scraped correctly, but `setInterval` is missing: https://devdocs.io/dom/windoworworkerglobalscope/setinterval

 I'm a bit surprised we got one, but not the other!

**Comment by simon04** [comment]
Err, sorry for the confusion.

```
> bundle exec thor docs:page dom /WindowOrWorkerGlobalScope/setInterval
bundler: failed to load command: thor (/Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/bin/thor)
NoMethodError: undefined method `content=' for nil:NilClass
  /Users/simon/src/devdocs/lib/docs/filters/mdn/clean_html.rb:45:in `block in call'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/simon/src/devdocs/lib/docs/filters/mdn/clean_html.rb:44:in `call'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline/filter.rb:129:in `call'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:134:in `block in perform_filter'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:174:in `block in instrument'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:173:in `instrument'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:133:in `perform_filter'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:119:in `block (2 levels) in call'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:118:in `each'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:118:in `inject'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:118:in `block in call'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:174:in `block in instrument'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:173:in `instrument'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/html-pipeline-2.12.0/lib/html/pipeline.rb:116:in `call'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:67:in `build_page'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:91:in `block in store_page'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:90:in `store_page'
  /Users/simon/src/devdocs/lib/docs.rb:95:in `generate_page'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:59:in `page'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/bin/thor:23:in `load'
  /Users/simon/src/devdocs/vendor/bundle/ruby/2.6.0/bin/thor:23:in `<top (required)>'
```

I've found and fixed the bug. As a result –

```
  Updated: 5954                                                                                                                                                
  Created: 5                                                                                                                                                   
    + CSS Typed OM API                                                                                                                                         
    + StyleSheetList                                                                                                                                           
    + TouchEvent                                                                                                                                               
    + WebGL API: Constants                                                                                                                                     
    + WindowOrWorkerGlobalScope.setInterval                                                                                                                    
  Deleted: 0                                                                                                                                                   
```
