### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by rahulgit90** [freeCodeCamp/devdocs#1535]
Guys,

I am having an issue with installing Devdocs.

Getting the error,

```
 bundle exec thor docs:download --default
(1/5) HTML OK
(2/5) CSS OK
(3/5) HTTP OK
(4/5) JavaScript OK
(5/5) DOM OK
bundler: failed to load command: thor (/usr/local/bin/thor)
Traceback (most recent call last):
        45: from /usr/local/bin/bundle:23:in `<main>'
        44: from /usr/local/bin/bundle:23:in `load'
        43: from /usr/local/share/gems/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
        42: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        41: from /usr/local/share/gems/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
        40: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
        39: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        38: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
        37: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        36: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        35: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        34: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
        33: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
        32: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
        31: from /usr/local/share/gems/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
        30: from /usr/local/bin/thor:24:in `<top (required)>'
        29: from /usr/local/bin/thor:24:in `load'
        28: from /usr/share/gems/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
        27: from /usr/share/gems/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        26: from /usr/share/gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        25: from /usr/share/gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        24: from /usr/share/gems/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
        23: from /usr/share/gems/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
        22: from /usr/share/gems/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
        21: from /usr/share/gems/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        20: from /usr/share/gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        19: from /usr/share/gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        18: from /usr/share/gems/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        17: from /opt/devdocs/lib/tasks/docs.thor:139:in `download'
        16: from /opt/devdocs/lib/tasks/docs.thor:365:in `generate_manifest'
        15: from /opt/devdocs/lib/docs.rb:104:in `generate_manifest'
        14: from /opt/devdocs/lib/docs.rb:43:in `all_versions'
        13: from /opt/devdocs/lib/docs.rb:37:in `all'
        12: from /opt/devdocs/lib/docs.rb:37:in `map'
        11: from /opt/devdocs/lib/docs.rb:37:in `block in all'
        10: from /opt/devdocs/lib/docs.rb:37:in `const_get'
         9: from /opt/devdocs/lib/docs.rb:37:in `require'
         8: from /opt/devdocs/lib/docs/scrapers/gnuplot.rb:1:in `<top (required)>'
         7: from /opt/devdocs/lib/docs/scrapers/gnuplot.rb:2:in `<module:Docs>'
         6: from /opt/devdocs/lib/docs/scrapers/gnuplot.rb:12:in `<class:Gnuplot>'
         5: from /opt/devdocs/lib/docs/core/filter_stack.rb:13:in `push'
         4: from /opt/devdocs/lib/docs/core/filter_stack.rb:46:in `filter_const'
         3: from /opt/devdocs/lib/docs/core/filter_stack.rb:46:in `map'
         2: from /opt/devdocs/lib/docs/core/filter_stack.rb:48:in `filter_const'
         1: from /opt/devdocs/lib/docs/core/filter_stack.rb:48:in `const_get'
/opt/devdocs/lib/docs/core/filter_stack.rb:48:in `require': /opt/devdocs/lib/docs/filters/gnuplot/clean_html.rb:79: syntax error, unexpected ']' (SyntaxError)
...   .map { |line| line[indent..] || '' }
...                              ^
```

**Comment by rahulgit90** [comment]
ruby --version
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

bundler --version
Bundler version 2.2.16

**Comment by ojeytonwilliams** [comment]
Hi @rahulgit90.  I just verified that it works locally for me.  For reference, I'm on 

ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
and
Bundler version 2.2.15

Could you try ruby 2.6.5 and see if that helps?
