### ISSUE TITLE
thor docs:generate using the wrong path

### ISSUE THREAD

**Issue by noraj** [freeCodeCamp/devdocs#1901]
# Bug report

I have the git repository cloned to `/tmp/devdocs`.

A command like `bundle exec thor docs:download ruby@3.1` successfully fetch all the doc in `public/docs/ruby~3.1`  (`/tmp/devdocs/public/docs/ruby~3.1`). But the command `docs:generate` is wrongly looking for the documentation in `/tmp/devdocs/docs/ruby~3.1` instead of `/tmp/devdocs/public/docs/ruby~3.1`.

```
$ bundle exec thor docs:generate ruby@3.1
Building internal urls...                                                                                                                                                                                            
[                                                                                                                                                                          ] [0/1] [  0.00%] [00:00] [00:00] [0.00/s]
bundler: failed to load command: thor (/home/noraj/.asdf/installs/ruby/2.7.7/bin/thor)
Docs::SetupError: The Ruby scraper requires the original documentation files to be stored in the "/tmp/devdocs/docs/ruby~3.1" directory.
  /tmp/devdocs/lib/docs/core/scrapers/file_scraper.rb:26:in `assert_source_directory_exists'
  /tmp/devdocs/lib/docs/core/scrapers/file_scraper.rb:36:in `request_all'
  /tmp/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /tmp/devdocs/lib/docs/core/scraper.rb:241:in `fetch_internal_urls'
  /tmp/devdocs/lib/docs/core/scraper.rb:232:in `with_internal_urls'
  /tmp/devdocs/lib/docs/core/scraper.rb:223:in `store_pages'
  /tmp/devdocs/lib/docs.rb:100:in `generate'
  /tmp/devdocs/lib/tasks/docs.thor:303:in `generate_doc'
  /tmp/devdocs/lib/tasks/docs.thor:105:in `generate'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
  /home/noraj/.asdf/installs/ruby/2.7.7/bin/thor:23:in `load'
  /home/noraj/.asdf/installs/ruby/2.7.7/bin/thor:23:in `<top (required)>'
```

## OS information

ArchLinux

## Steps to reproduce

1. `git clone https://github.com/freeCodeCamp/devdocs.git && cd devdocs`
2. setup [ASDF](https://asdf-vm.com/). [asdf-ruby](https://github.com/asdf-vm/asdf-ruby) is based-on [ruby-build](https://github.com/rbenv/ruby-build) which is similar to [rbenv](https://github.com/rbenv/rbenv).
3. `asdf install ruby 2.7.7`
4. `asdf reshim`
5. `bundle install`
6. `bundle exec thor docs:download ruby@3.1`
7. `bundle exec thor docs:generate ruby@3.1`

## More resources

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.7 (2022-11-24 patchlevel 221) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /home/noraj/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /home/noraj/.asdf/installs/ruby/2.7.7/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/noraj/.asdf/installs/ruby/2.7.7/bin
  - SPEC CACHE DIRECTORY: /home/noraj/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/noraj/.asdf/installs/ruby/2.7.7/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/noraj/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0
     - /home/noraj/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/noraj/.asdf/installs/ruby/2.7.7/bin
     - /home/noraj/perl5/bin
     - /home/noraj/.asdf/shims
     - /home/noraj/.asdf/bin
     - /home/noraj/perl5/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /home/noraj/.dotnet/tools
     - /usr/lib/jvm/default/bin
     - /opt/nessus/bin
     - /opt/nessus/sbin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl
```

## Possible fix

IDK

**Comment by simon04** [comment]
No, those are different directories for different purposes. `/tmp/devdocs/docs/ruby~3.1` is the source directory for upstream docs according to https://github.com/freeCodeCamp/devdocs/blob/main/docs/file-scrapers.md

**Comment by noraj** [comment]
So there are more steps than the ones described at https://github.com/freeCodeCamp/devdocs/blob/main/.github/CONTRIBUTING.md#updating-existing-documentations? If so we should add a link about `docs/file-scrapers.md` into `CONTRIBUTING.md#updating-existing-documentations`.
