### ISSUE TITLE
Update React Native docs (to 0.52)

### ISSUE THREAD

**Issue by gianpaj** [freeCodeCamp/devdocs#761]
I just wanted to open this issue to let people know, and some accountability for me, that I've started to update scraper and filter files to fix the current issue.

The current last scrapped version is `0.49`.

Error for those curious:
```
$thor docs:generate react_native --force --debug
Queue:   facebook.github.io/react-native/docs/getting-started.html
Process: facebook.github.io/react-native/docs/getting-started.html                            [22ms]
ERROR:
  https://facebook.github.io/react-native/docs/getting-started.html
  Docs::ContainerFilter::ContainerNotFound: element '.documentationContent' could not be found in the document, url=https://facebook.github.io/react-native/docs/getting-started.html

  /Users/gianfranco/temp/devdocs/lib/docs/filters/core/container.rb:12:in `call'
  /Users/gianfranco/temp/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/gianfranco/temp/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/gianfranco/temp/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/gianfranco/temp/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/gianfranco/temp/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/gianfranco/temp/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/gianfranco/temp/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /Users/gianfranco/temp/devdocs/lib/docs/core/requester.rb:56:in `block in handle_response'
  /Users/gianfranco/temp/devdocs/lib/docs/core/requester.rb:55:in `each'
  /Users/gianfranco/temp/devdocs/lib/docs/core/requester.rb:55:in `handle_response'
  /Users/gianfranco/temp/devdocs/lib/docs/core/requester.rb:16:in `run'
  /Users/gianfranco/temp/devdocs/lib/docs/core/scrapers/url_scraper.rb:38:in `request_all'
  /Users/gianfranco/temp/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /Users/gianfranco/temp/devdocs/lib/docs/core/doc.rb:100:in `block in store_pages'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/gianfranco/temp/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /Users/gianfranco/temp/devdocs/lib/docs/core/doc.rb:99:in `store_pages'
  /Users/gianfranco/temp/devdocs/lib/docs.rb:83:in `generate'
  /Users/gianfranco/temp/devdocs/lib/tasks/docs.thor:198:in `generate_doc'
  /Users/gianfranco/temp/devdocs/lib/tasks/docs.thor:92:in `generate'

Failed!
```

Todo:
- [ ] style JavaScript code
- [ ] structure Getting Started page for each tab and subtab

**Comment by gianpaj** [comment]
@beaucarnes managed! thank a lot
