### ISSUE TITLE
Docker build fails per instructions

### ISSUE THREAD

**Issue by shusso** [freeCodeCamp/devdocs#835]
Per docker instructions command `docker build -t thibaut/devdocs .` fails with rev `bf116473e7d66610a5fb20cd663e1d7abae37228`
```
....
(281/282) TensorFlow Guide OK
(282/282) scikit-learn OK
Done
/usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/utils.rb:110:in `encode': "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/utils.rb:110:in `concat_javascript_sources'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:59:in `block (2 levels) in process_bundle_reducers'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:55:in `each'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:55:in `block in process_bundle_reducers'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:54:in `each'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:54:in `reduce'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:54:in `process_bundle_reducers'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:34:in `call'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
        from /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
        from /devdocs/lib/tasks/assets.thor:17:in `compile'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/runner.rb:42:in `method_missing'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:29:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:128:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/bundle/gems/thor-0.20.0/bin/thor:6:in `<top (required)>'
        from /usr/local/bundle/bin/thor:23:in `load'
        from /usr/local/bundle/bin/thor:23:in `<main>'
The command '/bin/sh -c thor docs:download --all &&     thor assets:compile &&     rm -rf /tmp' returned a non-zero code: 1
```

**Comment by intrepidev** [comment]
This just fixed it for me
